<?php
/**
 * RecurringPayment - Aggregate Root para Pagamentos Recorrentes de Contratos
 *
 * RESPONSABILIDADE:
 * - Encapsular estado e comportamento de pagamentos recorrentes
 * - Garantir invariantes de negócio (retry logic, state transitions)
 * - Orquestrar transições de status de pagamento
 * - Emitir Domain Events para auditoria
 *
 * INVARIANTES:
 * - Status só pode transicionar conforme RecurringPaymentStatus state machine
 * - Máximo 3 tentativas de cobrança
 * - Amount deve ser sempre positivo
 * - Payment UUID único por pagamento
 * - Contract + billing_cycle_number único (apenas 1 payment por ciclo)
 *
 * LIFECYCLE:
 * 1. Create (pending) → Pagamento criado, não processado
 * 2. markAsProcessing → Enviado ao MercadoPago
 * 3a. markAsCompleted → Pagamento aprovado
 * 3b. markAsFailed → Pagamento rejeitado, pode retry se attempt_count < 3
 * 4. incrementAttempt → Retry em caso de falha
 *
 * @package LimpVix\Domain\Finance
 * @since 0.9.0 (GAP #2 - Recurring Payment System)
 */

namespace LimpVix\Domain\Finance;

use LimpVix\Domain\Finance\ValueObjects\RecurringPaymentStatus;
use LimpVix\Domain\Finance\Events\RecurringPaymentCompleted;
use LimpVix\Domain\Finance\Events\RecurringPaymentFailed;

defined('ABSPATH') || exit;

final class RecurringPayment
{
    private ?int $id;
    private string $paymentUuid;
    private int $contractId;
    private int $billingCycleNumber;
    private float $amount;
    private RecurringPaymentStatus $status;
    private \DateTimeImmutable $dueDate;
    private ?string $gatewayTransactionId;
    private int $attemptCount;
    private ?\DateTimeImmutable $paidAt;
    private ?string $failureReason;
    private \DateTimeImmutable $createdAt;
    private \DateTimeImmutable $updatedAt;

    /** @var array<object> Domain events */
    private array $domainEvents = [];

    /**
     * Maximum retry attempts for failed payments
     */
    private const MAX_ATTEMPTS = 3;

    /**
     * Private constructor - use static factories
     */
    private function __construct(
        ?int $id,
        string $paymentUuid,
        int $contractId,
        int $billingCycleNumber,
        float $amount,
        RecurringPaymentStatus $status,
        \DateTimeImmutable $dueDate,
        ?string $gatewayTransactionId,
        int $attemptCount,
        ?\DateTimeImmutable $paidAt,
        ?string $failureReason,
        \DateTimeImmutable $createdAt,
        \DateTimeImmutable $updatedAt
    ) {
        $this->id = $id;
        $this->paymentUuid = $paymentUuid;
        $this->contractId = $contractId;
        $this->billingCycleNumber = $billingCycleNumber;
        $this->amount = $amount;
        $this->status = $status;
        $this->dueDate = $dueDate;
        $this->gatewayTransactionId = $gatewayTransactionId;
        $this->attemptCount = $attemptCount;
        $this->paidAt = $paidAt;
        $this->failureReason = $failureReason;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
    }

    /**
     * Factory: Create new recurring payment (status = pending)
     *
     * @param int $contractId
     * @param int $billingCycleNumber
     * @param float $amount
     * @param \DateTimeImmutable $dueDate
     * @return self
     * @throws \InvalidArgumentException
     */
    public static function create(
        int $contractId,
        int $billingCycleNumber,
        float $amount,
        \DateTimeImmutable $dueDate
    ): self {
        // Validations
        self::ensureValidAmount($amount);
        self::ensureValidCycleNumber($billingCycleNumber);

        $now = new \DateTimeImmutable();
        $paymentUuid = self::generateUuid();

        $payment = new self(
            null, // ID will be generated by repository
            $paymentUuid,
            $contractId,
            $billingCycleNumber,
            $amount,
            RecurringPaymentStatus::pending(),
            $dueDate,
            null, // No gateway transaction yet
            0, // No attempts yet
            null, // Not paid yet
            null, // No failure reason
            $now,
            $now
        );

        return $payment;
    }

    /**
     * Factory: Reconstruct from persistence
     */
    public static function fromPersistence(
        int $id,
        string $paymentUuid,
        int $contractId,
        int $billingCycleNumber,
        float $amount,
        string $status,
        string $dueDate,
        ?string $gatewayTransactionId,
        int $attemptCount,
        ?string $paidAt,
        ?string $failureReason,
        string $createdAt,
        string $updatedAt
    ): self {
        return new self(
            $id,
            $paymentUuid,
            $contractId,
            $billingCycleNumber,
            $amount,
            RecurringPaymentStatus::fromString($status),
            new \DateTimeImmutable($dueDate),
            $gatewayTransactionId,
            $attemptCount,
            $paidAt ? new \DateTimeImmutable($paidAt) : null,
            $failureReason,
            new \DateTimeImmutable($createdAt),
            new \DateTimeImmutable($updatedAt)
        );
    }

    /**
     * Mark payment as processing (sent to MercadoPago)
     *
     * @param string $gatewayTransactionId MercadoPago payment ID
     * @throws \DomainException if invalid transition
     */
    public function markAsProcessing(string $gatewayTransactionId): void
    {
        $newStatus = RecurringPaymentStatus::processing();

        if (!$this->status->canTransitionTo($newStatus)) {
            throw new \DomainException(
                sprintf(
                    'Cannot transition from %s to %s',
                    $this->status->getValue(),
                    $newStatus->getValue()
                )
            );
        }

        $this->status = $newStatus;
        $this->gatewayTransactionId = $gatewayTransactionId;
        $this->updatedAt = new \DateTimeImmutable();
    }

    /**
     * Mark payment as completed (approved by MercadoPago)
     *
     * @param \DateTimeImmutable $paidAt
     * @throws \DomainException if invalid transition
     */
    public function markAsCompleted(\DateTimeImmutable $paidAt): void
    {
        $newStatus = RecurringPaymentStatus::completed();

        if (!$this->status->canTransitionTo($newStatus)) {
            throw new \DomainException(
                sprintf(
                    'Cannot transition from %s to %s',
                    $this->status->getValue(),
                    $newStatus->getValue()
                )
            );
        }

        $this->status = $newStatus;
        $this->paidAt = $paidAt;
        $this->failureReason = null; // Clear any previous failure
        $this->updatedAt = new \DateTimeImmutable();

        // Fire domain event
        $this->recordEvent(new RecurringPaymentCompleted($this));
    }

    /**
     * Mark payment as failed (rejected by MercadoPago)
     *
     * @param string $reason Failure reason from gateway
     * @throws \DomainException if invalid transition
     */
    public function markAsFailed(string $reason): void
    {
        $newStatus = RecurringPaymentStatus::failed();

        if (!$this->status->canTransitionTo($newStatus)) {
            throw new \DomainException(
                sprintf(
                    'Cannot transition from %s to %s',
                    $this->status->getValue(),
                    $newStatus->getValue()
                )
            );
        }

        $this->status = $newStatus;
        $this->failureReason = $reason;
        $this->updatedAt = new \DateTimeImmutable();

        // Fire domain event
        $this->recordEvent(new RecurringPaymentFailed($this, $reason, $this->canRetry()));
    }

    /**
     * Increment attempt count (for retry logic)
     *
     * @throws \DomainException if max attempts exceeded
     */
    public function incrementAttempt(): void
    {
        if ($this->attemptCount >= self::MAX_ATTEMPTS) {
            throw new \DomainException(
                sprintf(
                    'Cannot increment attempt: max attempts (%d) reached',
                    self::MAX_ATTEMPTS
                )
            );
        }

        $this->attemptCount++;
        $this->updatedAt = new \DateTimeImmutable();
    }

    /**
     * Check if payment can be retried
     * Only failed payments with attempts < MAX can retry
     */
    public function canRetry(): bool
    {
        return $this->status->isFailed() && $this->attemptCount < self::MAX_ATTEMPTS;
    }

    /**
     * Cancel payment (manual intervention)
     *
     * @param string $reason Cancellation reason
     */
    public function cancel(string $reason): void
    {
        $newStatus = RecurringPaymentStatus::cancelled();

        if (!$this->status->canTransitionTo($newStatus)) {
            throw new \DomainException(
                sprintf(
                    'Cannot transition from %s to %s',
                    $this->status->getValue(),
                    $newStatus->getValue()
                )
            );
        }

        $this->status = $newStatus;
        $this->failureReason = $reason;
        $this->updatedAt = new \DateTimeImmutable();
    }

    // ========== Getters ==========

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPaymentUuid(): string
    {
        return $this->paymentUuid;
    }

    public function getContractId(): int
    {
        return $this->contractId;
    }

    public function getBillingCycleNumber(): int
    {
        return $this->billingCycleNumber;
    }

    public function getAmount(): float
    {
        return $this->amount;
    }

    public function getStatus(): RecurringPaymentStatus
    {
        return $this->status;
    }

    public function getDueDate(): \DateTimeImmutable
    {
        return $this->dueDate;
    }

    public function getGatewayTransactionId(): ?string
    {
        return $this->gatewayTransactionId;
    }

    public function getAttemptCount(): int
    {
        return $this->attemptCount;
    }

    public function getPaidAt(): ?\DateTimeImmutable
    {
        return $this->paidAt;
    }

    public function getFailureReason(): ?string
    {
        return $this->failureReason;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): \DateTimeImmutable
    {
        return $this->updatedAt;
    }

    /**
     * Get domain events (for event dispatcher)
     *
     * @return array<object>
     */
    public function releaseEvents(): array
    {
        $events = $this->domainEvents;
        $this->domainEvents = [];
        return $events;
    }

    // ========== Private Helpers ==========

    /**
     * Record domain event
     */
    private function recordEvent(object $event): void
    {
        $this->domainEvents[] = $event;
    }

    /**
     * Generate UUID for payment
     */
    private static function generateUuid(): string
    {
        return wp_generate_uuid4();
    }

    /**
     * Ensure amount is valid (positive)
     *
     * @throws \InvalidArgumentException
     */
    private static function ensureValidAmount(float $amount): void
    {
        if ($amount <= 0) {
            throw new \InvalidArgumentException(
                sprintf('Amount must be positive, got: %.2f', $amount)
            );
        }
    }

    /**
     * Ensure billing cycle number is valid (positive)
     *
     * @throws \InvalidArgumentException
     */
    private static function ensureValidCycleNumber(int $cycleNumber): void
    {
        if ($cycleNumber < 1) {
            throw new \InvalidArgumentException(
                sprintf('Billing cycle number must be >= 1, got: %d', $cycleNumber)
            );
        }
    }
}
