<?php
/**
 * ContractId - Value Object para identificador de contrato
 *
 * @package LimpVix\Domain\Contract
 * @since 0.7.0
 */

namespace LimpVix\Domain\Contract;

defined('ABSPATH') || exit;

final class ContractId
{
    private int $value;

    private function __construct(int $value)
    {
        $this->ensureValid($value);
        $this->value = $value;
    }

    public static function fromInt(int $value): self
    {
        return new self($value);
    }

    public static function generate(): self
    {
        // Será gerado pelo Repository via auto_increment
        throw new \LogicException('ContractId is generated by repository on save');
    }

    private function ensureValid(int $value): void
    {
        if ($value < 0) {
            throw new \InvalidArgumentException('ContractId must be non-negative');
        }
        // Allow 0 for new entities before persistence (will be set by repository)
    }

    public function toInt(): int
    {
        return $this->value;
    }

    public function equals(ContractId $other): bool
    {
        return $this->value === $other->value;
    }

    public function __toString(): string
    {
        return (string) $this->value;
    }
}
